import { stoyle, theme } from '../dependencies/stoyle.ts';
import { SelectOption } from '../dependencies/cliffy.ts';

export const EMOJIS: SelectOption[] = [
  { value: ':new:', name: stoyle`${':new:'} when adding a feature`({ nodes: [ theme.strong ] }) },
  { value: ':up:', name: stoyle`${':up:'} when improving a feature`({ nodes: [ theme.strong ] }) },
  { value: ':memo:', name: stoyle`${':memo:'} when writing docs`({ nodes: [ theme.strong ] }) },
  { value: ':calendar:', name: stoyle`${':calendar:'} when planning something (specs/roadmap/TODO)`({ nodes: [ theme.strong ] }) },
  { value: ':green_heart:', name: stoyle`${':green_heart:'} when fixing the CI build`({ nodes: [ theme.strong ] }) },
  { value: ':penguin:', name: stoyle`${':penguin:'} when fixing something on Linux`({ nodes: [ theme.strong ] }) },
  { value: ':apple:', name: stoyle`${':apple:'} when fixing something on Mac OS`({ nodes: [ theme.strong ] }) },
  { value: ':checkered_flag:', name: stoyle`${':checkered_flag:'} when fixing something on Windows`({ nodes: [ theme.strong ] }) },
  { value: ':bug:', name: stoyle`${':bug:'} when fixing a bug`({ nodes: [ theme.strong ] }) },
  { value: ':arrow_up:', name: stoyle`${':arrow_up:'} when upgrading dependencies`({ nodes: [ theme.strong ] }) },
  { value: ':arrow_down:', name: stoyle`${':arrow_down:'} when downgrading dependencies`({ nodes: [ theme.strong ] }) },
  { value: ':lock:', name: stoyle`${':lock:'} when improving security`({ nodes: [ theme.strong ] }) },
  { value: ':wrench:', name: stoyle`${':wrench:'} when improving the tooling`({ nodes: [ theme.strong ] }) },
  { value: ':triangular_ruler:', name: stoyle`${':triangular_ruler:'} when improving the format/structure of the code`({ nodes: [ theme.strong ] }) },
  { value: ':art:', name: stoyle`${':art:'} when improving styling`({ nodes: [ theme.strong ] }) },
  { value: ':shower:', name: stoyle`${':shower:'} when removing code or files`({ nodes: [ theme.strong ] }) },
  { value: ':white_check_mark:', name: stoyle`${':white_check_mark:'} when adding/improving tests`({ nodes: [ theme.strong ] }) },
  { value: ':shirt:', name: stoyle`${':shirt:'} when removing linter warnings`({ nodes: [ theme.strong ] }) },
  { value: ':racehorse:', name: stoyle`${':racehorse:'} when improving performance`({ nodes: [ theme.strong ] }) },
  { value: ':non-potable_water:', name: stoyle`${':non-potable_water:'} when plugging memory leaks`({ nodes: [ theme.strong ] }) },
  { value: ':eyes:', name: stoyle`${':eyes:'} when processing code-review comments`({ nodes: [ theme.strong ] }) },
  { value: ':construction:', name: stoyle`${':construction:'} when bumping versions and such`({ nodes: [ theme.strong ] }) },
  { value: ':bar_chart:', name: stoyle`${':bar_chart:'} when improving usage statistics gathering`({ nodes: [ theme.strong ] }) },
  { value: ':umbrella:', name: stoyle`${':umbrella:'} when improving security`({ nodes: [ theme.strong ] }) },
  { value: ':mute:', name: stoyle`${':mute:'} when removing notifications/logs`({ nodes: [ theme.strong ] }) },
  { value: ':sound:', name: stoyle`${':sound:'} when adding notifications/logs`({ nodes: [ theme.strong ] }) },
];
