module.exports = {
  NEW: { value: ':new:', name: `${':new:'.bold} when adding a feature` },
  UP: { value: ':up:', name: `${':up:'.bold} when improving a feature` },
  MEMO: { value: ':memo:', name: `${':memo:'.bold} when writing docs` },
  CALENDAR: { value: ':calendar:', name: `${':calendar:'.bold} when planning something (specs/roadmap/TODO)` },
  GREEN_HEART: { value: ':green_heart:', name: `${':green_heart:'.bold} when fixing the CI build` },
  PENGUIN: { value: ':penguin:', name: `${':penguin:'.bold} when fixing something on Linux` },
  APPLE: { value: ':apple:', name: `${':apple:'.bold} when fixing something on Mac OS` },
  CHECKERED_FLAG: { value: ':checkered_flag:', name: `${':checkered_flag:'.bold} when fixing something on Windows` },
  BUG: { value: ':bug:', name: `${':bug:'.bold} when fixing a bug` },
  ARROW_UP: { value: ':arrow_up:', name: `${':arrow_up:'.bold} when upgrading dependencies` },
  ARROW_DOWN: { value: ':arrow_down:', name: `${':arrow_down:'.bold} when downgrading dependencies` },
  LOCK: { value: ':lock:', name: `${':lock:'.bold} when improving security` },
  WRENCH: { value: ':wrench:', name: `${':wrench:'.bold} when improving the tooling` },
  TRIANGULAR_RULER: { value: ':triangular_ruler:', name: `${':triangular_ruler:'.bold} when improving the format/structure of the code` },
  ART: { value: ':art:', name: `${':art:'.bold} when improving styling` },
  SHOWER: { value: ':shower:', name: `${':shower:'.bold} when removing code or files` },
  WHITE_CHECK_MARK: { value: ':white_check_mark:', name: `${':white_check_mark:'.bold} when adding/improving tests` },
  SHIRT: { value: ':shirt:', name: `${':shirt:'.bold} when removing linter warnings` },
  RACEHORSE: { value: ':racehorse:', name: `${':racehorse:'.bold} when improving performance` },
  NON_POTABLE_WATER: { value: ':non-potable_water:', name: `${':non-potable_water:'.bold} when plugging memory leaks` },
  EYES: { value: ':eyes:', name: `${':eyes:'.bold} when processing code-review comments` },
  CONSTRUCTION: { value: ':construction:', name: `${':construction:'.bold} when bumping versions ans such` },
  BAR_CHART: { value: ':bar_chart:', name: `${':bar_chart:'.bold} when improving usage statistics gathering` },
  UMBRELLA: { value: ':umbrella:', name: `${':umbrella:'.bold} when improving security` },
  MUTE: { value: ':mute:', name: `${':mute:'.bold} when removing notifications/logs` },
  SOUND: { value: ':sound:', name: `${':sound:'.bold} when adding notifications/logs` },
};
